Curso de Capacitação em IA (2023)
[MCTI, SOFTEX, IFMA Monte Castelo]

# Atividade de Fixação
## Tópico: 3.1 - Numpy


### Instruções

1. Este notebook deve ser utilizado para fixação dos conceitos.
1. Abra este notebook no jupyter, jupyter lab, vscode (com extensões) ou no colab.  
1. Responda cada questão com seu código e execute. Verifique a saída, corrija se necessário, e execute novamente. 
1. Algumas questões admitem várias formas de resposta. Neste caso, adicione células com suas várias respostas. 



### Configurações

In [6]:
import numpy as np

## Questões

### Criação de ndarrays

1. Crie um ndarray de 5 itens a partir de números quaisquer (cada aluno deve utilizar numeros diferentes)

In [6]:
# Sua resposta aqui
import numpy as np
a = np.linspace(10,15,9)
print(a)

[10.    10.625 11.25  11.875 12.5   13.125 13.75  14.375 15.   ]


2. Crie um ndarray de 5 numeros inteiros em um dado intervalo 

In [2]:
# Digite seu codigo aqui
import numpy as np
a = np.arange(10,15)
print(a)

[10 11 12 13 14]


3. Crie um ndarray com 100 números reais no mesmo intervalo da questão anterior 

In [9]:
# Digite seu codigo aqui
import numpy as np
c = np.linspace(0,50,100)
print(c)

[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 18.18181818 18.68686869 19.19191919 19.6969697  20.2020202  20.70707071
 21.21212121 21.71717172 22.22222222 22.72727273 23.23232323 23.73737374
 24.24242424 24.74747475 25.25252525 25.75757576 26.26262626 26.76767677
 27.27272727 27.77777778 28.28282828 28.78787879 29.29292929 29.7979798
 30.3030303  30.80808081 31.31313131 31.81818182 32.32323232 32.82828283
 33.33333333 33.83838384 34.34343434 34.84848485 35.35353535 35.85858586
 36.36363636 36.86868687 37.37373737 37.87878788 38.38383838 38.88888889
 39.39393939 39.8989899  40.4040404  40.90909091 41.

4. Crie uma matriz quadrada de dimensão maior que 4, onde a diagonal principal é formada por valores 3 

In [13]:
# Digite seu codigo aqui
import numpy as np

d = np.diag([3,3,3,3,3])

print (d)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


### Fatiamento e indexação

5. Crie uma estrutura de duas dimensões com alguns poucos números, ex. 12. Selecione todos os números mas ignore as últimas duas linhae e considere apenas a ultima coluna. 

In [32]:
# Digite seu codigo aqui
import numpy as np
a2d = np.array(
    [
    [1,2,3],
    [4,9,8],
    [12,10,25]
    ])

print(a2d[:1,2:])

[[3]]


6. Extraia todos os números que sejam maior (ou menor) que a media (ou mediana) dos valores que você escolheu

In [39]:
# Digite seu codigo aqui
import numpy as np
a2d = np.array(
    [
    [1,2,3],
    [4,9,8],
    [12,10,25]
    ])

mediana = np.median(a2d)
print(mediana)
print("Maior: ")
print(a2d[a2d > mediana])
print()
print(f"Menor: {a2d[a2d < mediana]}")


8.0
Maior: 
[ 9 12 10 25]

Menor: [1 2 3 4]


7. Substitua todos os números menores que a média do array por 0, preservando os valores do array original

In [41]:
# Digite seu codigo aqui
import numpy as np
a2d = np.array(
    [
    [1,2,3],
    [4,9,8],
    [12,10,25]
    ])

mediana = np.median(a2d)
a2d[a2d<mediana] = 0
print(a2d)

[[ 0  0  0]
 [ 0  9  8]
 [12 10 25]]


### Mudança de Formato

8. De um exemplo onde um ndarray de 1D é transformado em 2D. Por exemplo, transformar um vetor 1D em uma matriz coluna ou matriz linha

In [13]:
# Digite seu codigo aqui
import numpy as np
#coluna
a = np.arange(1,7).reshape(6,1)
print(a)
#linha
b =  np.arange(1,7).reshape(1,6)
print(b)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


9. Mostre como empilhar verticalmente dois ndarrays de 2 dimensões (matrizes) de dimensões compatíveis. Fique à vontade para mostra concatenação em qualquer um dos eixos 

In [21]:
# Digite seu codigo aqui
a = np.array([[1,2,4],
            [5,6,7]])

b = np.array([[10,9,8],
            [11,20,25]])
# axix = 1 concatena em torno do eixo y, ou seja, coluna
# axis = 0 concatena em torno do eixo x, ou seja, linhas
# None, ignora dimensoes e forma um array 1 dimesional com todos os elementos


#verticalmente
np.concatenate([a,b],axis = 1)
#np.concatenate([a,b],axis = None)

array([[ 1,  2,  4, 10,  9,  8],
       [ 5,  6,  7, 11, 20, 25]])

**Nota:** stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack

## Miscelânea

10. Como calcular media, desvio e mediana de um array?

In [27]:
# Digite seu codigo aqui
#supondo o array
a = np.array([1,5,7,9])
media = np.mean(a)
mediana = np.median(a)
desvio_padrao = np.std(a)
print(media)
print(mediana)
print(round(desvio_padrao,2))



5.5
6.0
2.96


11. Como normalizar os valores em um ndarray? 

** Nota**: *normalizar* é uma operação matemática que subtrai a média dos dados e divide pelo seu desvio padrão. 

In [46]:
# Digite seu codigo aqui
a = np.array([[1,5,7],
            [10,9,8]])
media = np.mean(a)
mediana = np.median(a)
desvio_padrao = np.std(a)

print((a-media)/desvio_padrao)
normalizado = (a - media)/desvio_padrao
print(normalizado)



[[-1.90065778 -0.55901699  0.1118034 ]
 [ 1.11803399  0.78262379  0.4472136 ]]
[[-1.90065778 -0.55901699  0.1118034 ]
 [ 1.11803399  0.78262379  0.4472136 ]]
[[0.11547005 0.57735027 0.80829038]
 [0.63887656 0.57498891 0.51110125]]


12. Calcular correlação entre dois vetores

In [79]:
# Digite seu codigo aqui
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


13. Crie um vetor com vários valores repetidos. Como contar a quantidade de ocorrencias de cada valor unicos em um ndarray?

In [78]:
# Digite seu codigo aqui
# dado o ndarray abaixo

a = np.array([[5,6,9,10,5,9],[9,8,6,5,9,10]])

unique,counts = np.unique(a, return_counts = True)
print(unique)
print(counts)

[ 5  6  8  9 10]
[3 2 1 4 2]


# Referências

Se você quiser, veja mais exercícios no link abaixo. Atente para o fato de que algumas das respostas neste link não valem mais para a versão atual do numpy. 

https://www.machinelearningplus.com/python/101-numpy-exercises-python/